# Generated by Django 5.1.4 on 2024-12-11 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
